### ISSUE TITLE
Manta v4.0.2 Pre-Release checklist

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#1018]
# Release Checklist

Most of the following checks should be completed before officially publishing the new release
of the Calamari/Manta runtime or client. Some need to be completed after the new code is deployed.

These checks should be performed on the codebase prior to freezing our release candidate:

- [x] Announce code freeze (typically one week prior to release), to ensure we have enough time for related testing. Notify everyone @Runtime that a release is ongoing and no more merges to `manta` should happen until told otherwise
- On a branch named `release-vX.Y.Z` or `release-vX.Y.Z-something` ( something could be e.g. `alpha` or `rc1` ). Substitute X Y Z with the release version number.
    - [x] Verify that each crate's `version` has been bumped from previous release.
    - [x] Verify [`spec_version`](#spec-version) has been incremented since the
        last release for any native runtimes from any existing use on public
        (non-private/test) networks. If the runtime was published (release or pre-release), either
        the `spec_version` or `impl` must be bumped.
    - [x] Verify pallet and [extrinsic ordering](#extrinsic-ordering) has stayed
        the same. Bump `transaction_version` if not.
    - [x] Verify new extrinsics have been correctly whitelisted/blacklisted
    - [x] Verify [benchmarks](#benchmarks) have been updated for any modified
        runtime logic.
    - [x] Check for any upstream storage migrations and perform tests with `try-runtime`, if any.
    - [x] Grep github actions files for `POLKADOT_BINARY` and `_BINARY` and update them
    - [x] Generate new changelog using `dev-tools` repo
    - [x] Merge when green and reviewed
    - [x] Tag the release with the same version you used on the release PR. IMPORTANT: Use the `manta` branch commit for the tag, NOT a `release-` or other branch
    - [x] Wait for CI to succeed running on the tag
    - [x] Check that a draft release has been created at https://github.com/Manta-Network/Manta/releases and add relevant [Release Notes](#release-notes)
    - [x] Check that build artifacts have been added to the draft-release
    - [x] Promote the draft to a Pre-Release on github

### Release Notes

The release notes **MUST** contain:

- The priority of the release (i.e., how quickly users should upgrade) - this is
    based on the max priority of any *client* changes.
- The version of [Manta SDK](https://github.com/Manta-Network/sdk) that is compatible with this release
- Which native runtimes and their versions are included
- The proposal hashes of the runtimes as built with [srtool](https://gitlab.com/chevdor/srtool)
- (After auditing starts:) Any changes in this release that are still awaiting audit

The release notes **MAY** also list:

- Free text at the beginning of the notes mentioning anything important
    regarding this release
- Notable changes (those labelled with B[1-9]-* labels) separated into sections

### Spec Version

A runtime upgrade must bump the spec number. This may follow a pattern with the
client release

### Extrinsic Ordering

Offline signing libraries depend on a consistent ordering of call indices and
functions. Compare the metadata of the current and new runtimes and ensure that
the `module index, call index` tuples map to the same set of functions. To generate a diff report you can do the following:
* Go to the [metadata diff tool page](https://github.com/Manta-Network/Manta/actions/workflows/metadata_diff.yml).
* Open `Run workflow` drop-down menu.
* Choose the branch you want to test and other inputs if the defaults are not applicable.
* Run the workflow.
* Wait for the job to complete and inspect the output. The things to look for in the `output.txt` are lines like:
  - `[Identity] idx 28 -> 25 (calls 15)` - indicates the index for `Identity` has changed
  - `[+] Society, Recovery` - indicates the new version includes 2 additional modules/pallets.
  - If no indices have changed, every modules line should look something like `[Identity] idx 25 (calls 15)`

 In case of a breaking change, bump the `transaction_version`.

Note: Adding new functions to the runtime does not constitute a breaking change
as long as the indexes did not change.

### Benchmarks

There is a manually deployed github action that runs all benchmarks on a bare-metal AWS machine. In order to use go to :
* Go to [Run All Benchmarks Github Action](https://github.com/Manta-Network/Manta/actions/workflows/run_all_benchmarks.yml)
* Open `Run workflow` drop-down menu.
* Choose your branch.
* Choose a chain-spec. You'll have to run the workflow multiple times usually with `dolphin-dev`, `calamari-dev`, `manta-dev`.
* Optionally choose whether you want to provide a chain database snapshot to benchmark storage performance.
* When these jobs have completed (it takes a few hours), all the benchmarks outputs files will be available to download as workflow artifacts.
* Commit the changes to your branch and push to the remote branch for review.
* The weights should be (Currently manually) checked to make sure there are no big outliers (i.e., twice or half the weight).

### Security Audit

Before release, run a `Security Audit`

* Go to [Security Audit](https://github.com/Manta-Network/Manta/actions/workflows/audit.yml).
* Open `Run workflow` drop-down menu.
* Choose your branch and run the workflow.
* An audit report will be generated.
* Address any reported findings before release. If it cannot be fixed, please file an issue.

**Comment by Garandor** [comment]
completed with https://github.com/Manta-Network/Manta/releases/tag/v4.0.2
