### ISSUE TITLE
Calamari Shell Chain Tracking Issue

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#110]
- [x] Calamari parachain runtime pallet configuration
- [x] bump dependency to newest (0.9.8)
- [x] Use cargo features to decide which runtime can be compiled
- [x] filter all functions
- [x] PR to polkadot-js for updating calamari icon and some naming stuff -> [PR](https://github.com/polkadot-js/apps/pull/5832)
- [x] Test runtime upgrade locally
- [ ] End to end test using `Manta-Subxt` (try the current code) (Good to have)
- [ ] Weight definitions and related settings. (Good to have)
- [ ] Test shell chain on EC2 (own-relay chain, 5 collators).
   - [x] EC2 deployment (with Rob) 
   - [x] producing blocks
   - [x] basic functionalities (filtering out functions)
   - [x] release workflow (binary and WASM) (Jamie, Shumo, Gerogi, Qiudong, Rob)
       - [x] first calamari release
       - [ ] automation
         - [ ] dockerize [Rob]
         - [x] srtool for wasm
       - [x] change log (generator [implemented](https://github.com/Manta-Network/Manta/compare/c4de44d..2f254db), needs customisation)
   - [x] shell chain genesis and secret configuration  
   - [x] Dry run of the crowd loan
   - [x] Integrating with Kevin/Sinan's frontend
   - [x]  test runtime upgrade (Qiudong)
   - [x] Show calamari network in dropdown menu from polkadot-js-extension (Georgi)
- [ ] Test shell chain on external testnet (using our own chain spec) (Jamie)
   - [ ] EC2 deployment (with Rob) 
   - [ ] producing blocks
   - [ ] basic functionalities (filtering out functions)
   - [ ] runtime upgrade 
   - [ ] stress tests (make sure our weight configuration is good enough to handle DDoS) (Good to have)
   - [ ] Dry run of the crowd loan
   - [ ] Integrating with Kevn/Sinan's frontend, create a hosted version (Kevin, Rob)
- [x] crowdloan front-end
   - [x] contribution history
   - [x] referral
   - [x] leaderboard
   - [x] trend
- [x] investigate the performance regression issue when illegal collators spawned (Shumo, Georgi) 
- [x] Configure Calamari's SS58 Prefix
- [ ] Configure Calamari runtime chain spec(session keys, root key, peer id, etc)
   - [x] figure out the semantics of the constants 
- [x] Impl `try-runtime` for Calamari runtime (Jamie, Shumo)
- [x] Calamari website/doc depolyment (Georgi, Qiudong)
- [x] Shell chain testnet genesis
- [x] Shell chain genesis

**Comment by ghzlatarev** [comment]
Guys, synced with Jamie and I'm gonna start work on ``Impl try-runtime for Calamari runtime ``

**Comment by ghzlatarev** [comment]
For ``Show calamari network in dropdown menu from polkadot-js-extension`` we need to wait until we launch mainnet.
The flow is the following:
1. https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/Popup/CreateAccount/index.tsx#L28 
2. https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/hooks/useGenesisHashOptions.ts
3. https://github.com/polkadot-js/extension/blob/master/packages/extension-ui/src/util/chains.ts#L8-L10
4. https://github.com/polkadot-js/common/blob/master/packages/networks/src/index.ts
5. https://github.com/polkadot-js/common/blob/master/packages/networks/src/substrate.ts#L491-L508
