### ISSUE TITLE
Manta Testnet Launch Tracking

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#12]
## Major Milestones
- [x] Testnet V1 (Internal): May 9
- [ ] Testnet V2 (Internal Feature Ready): May 16
- [ ] Testnet V3 (Public Alpha): May 25

## Breakdowns
- [x] V1: Pallet-Asset configuration (https://github.com/Manta-Network/Manta/pull/11) [Zhenfei]
- [x] V1: Vanilla manta node implementation (https://github.com/Manta-Network/Manta/pull/10) [Shumo]
- [x] V1: SS58 registration, PR to substrate repo (https://github.com/paritytech/substrate/pull/8706) [Shumo]
- [x] V1: Vanilla manta node unit test [Shumo, May 1]
- [x] V1: Testnet depolymnet
  - [x] get shared secret mechanism for certification (possibly using AWS: I AM ROLE) 
  - [x] get toy network running on AWS including wss access point
  - [x] Validator/Archieval Node (block explorer will have acess to the archieval node)
  - [x] Staking: set session key
  - [x] wss acess point and certificate (`ws.testnet.manta.network`)
- [x] V1: genesis configuration [Jamie, Shumo, Apr 30] 
  - [x] controller, stash, grandpa, babe keys for boot nodes
  - [x] key store configuration
- [x] V1: Basic CI/CD [Georgi]
- [x] V2: show MA token symbol in polkadot.js APP
- [x] V2: a new website [Team figure out the idea, Kenny hire a external company]
- [x] V2: new document section in the website, should be generated from markdown file, and then host it at `docs.manta.network` [Rob]
- [x] V2: dockerize (https://github.com/Manta-Network/Manta/pull/14) [Jamie]
- [x]  V2: Subscan.io
  - [x]  business contact with subscan.io
  - [x]  provide `type.json` 
  - [x]  RPC node, exposing wss port
- [ ] V2: Integration/Deployment test  [Everyone!, Rob lead on the deployment test]
   - [x] deploy manta successfully on Cloud [Shumo, Georgi, Rob]
   - [ ] grow / shrink validators
   - [ ] validator nomination
   - [ ] network partition (pull off power of some node randomly)
- [ ] V2: Vanilla manta node code internal audit [Everyone]
- [x] V2: dashboard to monitoring testnet status (Prometheus configuration)
- [ ] V2: code auditors to schedule meeting [Zhenfei]
- [x] V2: Node configuration [Jamie, Shumo, Rob]
     - full node (just keep ~100 blocks)
     - validator node  (running consensus)
     - archival node (connect to subscan.io)
- [x] V2: Cluster configuration (5 first, scale to 21) [Jamie, Shumo, Rob]
- [x] V2: Manta-Pay Integration 
- [ ] V2: Front-end/Client support for Manta-Pay
- [x] V2: Front end UX/UI [Kevin]
- [x] V2: Connect to a wallet
