### ISSUE TITLE
Test Automation Tracking Issue

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#146]
- [ ] make `Manta-PC-launch` in the background in github action
- [ ] non-ZKP function test
- [ ] dedicate test instance
- [ ] ZKP-function
