### ISSUE TITLE
Testnet Release Tracking

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#161]
- [x] Storage Refactoring (Shumo)
  - [x] Pallet-Manta-Pay
  - [x] Manta Runtime integration
- [x] Arkwork 3.0 (Good to have) (Brandon)
- [ ] Dolphin DApp Front-End 
- [ ] Using Dev-Cli to stress test (G)
  - [ ] https://github.com/Manta-Network/manta-js/pull/4
- [ ] Prepare Signer Server
  - [ ] Design the UI for signer with manta logos, colors, fonts, ... etc.
  - [ ] Decide on bundling strategy, like which public keys to use, and test it on all the platforms we have access to
    - [x] MacOS
    - [ ] Windows
    - [x] Linux
  - [ ] Write some docs for testnet users on how to install and use the signer server. See https://github.com/Manta-Network/docs/issues/3.
