### ISSUE TITLE
Manta/Calamari V3.1.0 Tracking Issue

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#277]
Have to merge PRs:

- [x]  https://github.com/Manta-Network/Manta/pull/221
- [x]  https://github.com/Manta-Network/Manta/pull/265
- [x] https://github.com/Manta-Network/Manta/pull/258
- [x] https://github.com/Manta-Network/Manta/pull/270

Good to have PRs:

- [x] Remake of https://github.com/Manta-Network/Manta/pull/263

Test 
- [ ] Baikal Testing
