### ISSUE TITLE
Automate all manual QA workflow checks

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#347]
This is the current manual QA workflow: https://hackmd.io/TbFmorG2RnOPmLuFcg9JOQ?both
Includes:
- [x] session keys checks
- [x] balances/transfers checks
- [x] collator selection checks
- [x] multi-sig checks
- [x] xcm checks - split to https://github.com/Manta-Network/Manta/issues/675
- [x] governance checks
- [x] runtime upgrade checks #323
- [x] client upgrade checks #324

Should be automated preferably via calls to polkadot js api

**Comment by Dengjianping** [comment]
Yeah, I think we should take time to implement a tool for it.

**Comment by ghzlatarev** [comment]
Reference https://github.com/PureStake/moonbeam/tree/master/tests
