### ISSUE TITLE
Improve XCM tests

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#442]
Equalize Mock environment with Dolphin:
- [x] implement same Barrier and adjust tests
- [x] use same weights configurations
- [x] equalize relay configs with Kusama/Polkadot ---> https://github.com/Manta-Network/Manta/issues/648

Write must-fail xcm tests: 
- [x] `destWeight` ->  `Barrier` 
- [x] low `amount` -> `TooExpensive`
- [x] high `amount` -> `XcmExecutionFailed`
- [x] more self_insufficient tests

More:
- [x] fuzzer tests (AFL framework) ---> https://github.com/Manta-Network/Manta/issues/647
- [x] integration tests that xcm fees go to correct account - `Treasury` ---> https://github.com/Manta-Network/Manta/issues/649
