### ISSUE TITLE
Manta 3.1.5 Release checklist

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#483]
# Release Checklist

Most of the following checks should be completed before officially publishing the new release
of the Calamari/Manta runtime or client. Some need to be completed after the new code is deployed.

### Runtime Releases

These checks should be performed on the codebase prior to freezing our release candidate:

- [x] Verify [`spec_version`](#spec-version) has been incremented since the
    last release for any native runtimes from any existing use on public
    (non-private/test) networks. If the runtime was published (release or pre-release), either
    the `spec_version` or `impl` must be bumped.
- [x] Verify pallet and [extrinsic ordering](#extrinsic-ordering) has stayed
    the same. Bump `transaction_version` if not.
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted
- [x] Verify [benchmarks](#benchmarks) have been updated for any modified
    runtime logic.
- [x] Check for any upstream storage migrations and perform tests with `try-runtime`, if any.

The following checks can be performed after we have frozen our release candidate:

- [x] Code freeze should typically happen one week prior to release, to ensure we have enough time for related testing.
- [x] Notify everyone, especially people with merge rights to `manta` (stechu, Dengjianping) that a release is ongoing and no more merges to `manta` should happen until told otherwise
- [x] Complete the following [manual QA workflow](https://hackmd.io/TbFmorG2RnOPmLuFcg9JOQ?view).
- [x] Verify [Polkadot JS API](#polkadot-js) are up to date with the latest
    runtime changes.
- [x] Execute runtime upgrade to Como and verify network stability.
- [x] Execute runtime upgrade to Baikal and verify network stability.
- [x] Prepare a governance post and submit to our forum with description and motivation for changes.

### Client Releases

- [x] Verify that each crate's `version` has been bumped from previous release.
- [x] Check that the new client versions have [run on the network](#burn-in) without issue for 12 hours.

### All Releases

- [x] Check that a draft release has been created at
    https://github.com/Manta-Network/Manta/releases with relevant [release
    notes](#release-notes)
- [x] Check that [build artifacts](#build-artifacts) have been added to the
    draft-release
- [x] Coordinate with marketing team for documenation updates and other relevant tasks.
- [x] Update changelog.

### After Runtime Upgrade
- [x] Notify subscan team. Ensure subscan service can continue to scan calamari blocks.
- [x] Sidecar [update](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/chains-config/metadata-consts/calamariConsts.ts#L6)

### Burn In

Ensure that Manta DevOps has run the new release on Como and Baikal nodes
for at least 12 hours prior to publishing the release.

### Release notes

The release notes should list:

- The priority of the release (i.e., how quickly users should upgrade) - this is
    based on the max priority of any *client* changes.
- Which native runtimes and their versions are included
- The proposal hashes of the runtimes as built with
    [srtool](https://gitlab.com/chevdor/srtool)
- Any changes in this release that are still awaiting audit

The release notes may also list:

- Free text at the beginning of the notes mentioning anything important
    regarding this release
- Notable changes (those labelled with B[1-9]-* labels) separated into sections

### Spec Version

A runtime upgrade must bump the spec number. This may follow a pattern with the
client release

### Extrinsic Ordering

Offline signing libraries depend on a consistent ordering of call indices and
functions. Compare the metadata of the current and new runtimes and ensure that
the `module index, call index` tuples map to the same set of functions. In case
of a breaking change, increase `transaction_version`.

The things to look for in the output are lines like:
  - `[Identity] idx 28 -> 25 (calls 15)` - indicates the index for `Identity` has changed
  - `[+] Society, Recovery` - indicates the new version includes 2 additional modules/pallets.
  - If no indices have changed, every modules line should look something like `[Identity] idx 25 (calls 15)`

Note: Adding new functions to the runtime does not constitute a breaking change
as long as the indexes did not change.

### Benchmarks

There are three benchmarking machines reserved for updating the weights at
release-time. To initialise a benchmark run for each production runtime
(calamari, manta):
* Go to [Calamari Benchmarking Github Action](https://github.com/Manta-Network/Manta/actions/workflows/generate_calamari_weights_files.yml) 
  and [Manta Benchmarking Github Action](https://github.com/Manta-Network/Manta/actions/workflows/generate_manta_weights_files.yml)
* Open "Run workflow" drop-down menu.
* Choose your branch and run the workflow.
* When these jobs have completed (it takes a few hours), custom weights files will
    be available to download as artifacts. 
* Commit the changes to your branch and push to the remote branch for review.
* The weights should be (Currently manually) checked to make sure there are no
    big outliers (i.e., twice or half the weight).

**Comment by ghzlatarev** [comment]
try-runtime result:
```
2022-04-13 17:27:19 assembling new collators for new session 0 at #0    
2022-04-13 17:27:19 assembling new collators for new session 1 at #0    
2022-04-13 17:27:19 Connection established to target: Target { sockaddrs: [], host: "ws.calamari.systems", host_header: "ws.calamari.systems:443", mode: Tls, path_and_query: "/" }    
2022-04-13 17:27:19 scraping key-pairs from remote @ 0xf245875762d16cf67e90bd08c3fb946f598cb62d443cb4bf1c8a7b5d241ed540    
2022-04-13 17:27:19 downloading data for all pallets.    
2022-04-13 17:27:35 adding data for hashed key: 26aa394eea5630e07c48ae0c9558cef7f9cce9c888469bb1a0dceaa129672ef8    
2022-04-13 17:27:35 👩‍👦 scraping child-tree data from 0 top keys    
2022-04-13 17:27:35 injecting a total of 57909 top keys    
2022-04-13 17:27:36 injecting a total of 0 child keys    
2022-04-13 17:27:36 initialized state externalities with storage root 0x8fa30a08055fc75f86065737a0b9740347fd6f957289d137b81200fa8d94f4b1    
2022-04-13 17:27:38 Connection established to target: Target { sockaddrs: [], host: "ws.calamari.systems", host_header: "ws.calamari.systems:443", mode: Tls, path_and_query: "/" }    
2022-04-13 17:27:38 found matching spec name: "calamari"    
2022-04-13 17:27:38 found matching spec version: 3141    
2022-04-13 17:27:38 Precheck: KickThreshold does not exist    
2022-04-13 17:27:38 Executing collator-selection V0->V1 migration!    
2022-04-13 17:27:38  >>> Cleaned 12 keys from LastAuthoredBlock    
2022-04-13 17:27:38  >>> Removed LastAuthoredBlock from storage    
2022-04-13 17:27:38  !!! Chain did not have KickThreshold in storage. This is uenexpected but is possible if the genesis config was never changed    
2022-04-13 17:27:38 ✅ no migration for System    
2022-04-13 17:27:38 ✅ no migration for CalamariVesting    
2022-04-13 17:27:38 ✅ no migration for AssetManager    
2022-04-13 17:27:38 ✅ no migration for Assets    
2022-04-13 17:27:38 ✅ no migration for Sudo    
2022-04-13 17:27:38 ✅ no migration for Multisig    
2022-04-13 17:27:38 ✅ no migration for Utility    
2022-04-13 17:27:38 ✅ no migration for XTokens    
2022-04-13 17:27:38 ✅ no migration for DmpQueue    
2022-04-13 17:27:38 ✅ no migration for CumulusXcm    
2022-04-13 17:27:38 ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `StorageVersion(0)`    
2022-04-13 17:27:38 ⚠️ XcmpQueue declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`    
2022-04-13 17:27:38 ✅ no migration for Scheduler    
2022-04-13 17:27:38 ✅ no migration for Preimage    
2022-04-13 17:27:38 ✅ no migration for Treasury    
2022-04-13 17:27:38 ✅ no migration for AuraExt    
2022-04-13 17:27:38 ✅ no migration for Aura    
2022-04-13 17:27:38 ✅ no migration for Session    
2022-04-13 17:27:38 ✅ no migration for CollatorSelection    
2022-04-13 17:27:38 ✅ no migration for Authorship    
2022-04-13 17:27:38 ✅ no migration for TechnicalMembership    
2022-04-13 17:27:38 ✅ no migration for TechnicalCommittee    
2022-04-13 17:27:38 ✅ no migration for CouncilMembership    
2022-04-13 17:27:38 ✅ no migration for Council    
2022-04-13 17:27:38 ✅ no migration for Democracy    
2022-04-13 17:27:38 ✅ no migration for TransactionPayment    
2022-04-13 17:27:38 ✅ no migration for Balances    
2022-04-13 17:27:38 ✅ no migration for TransactionPause    
2022-04-13 17:27:38 ✅ no migration for ParachainInfo    
2022-04-13 17:27:38 ✅ no migration for Timestamp    
2022-04-13 17:27:38 ⚠️ ParachainSystem declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`    
2022-04-13 17:27:38 proof: 8000b480e3e4a01596340914580ed520093d533c5a672c0d423444b36ed0e70bcec6df5e800400c3e43c51c16b3b908fce6eb0e098614aa38828c1e16cbcf14884457597ee80c0c54691601a0129f0b9c93eb8ca2f123677f0fe31cfdb78ad3aed52b3f39bd280f1e3a0d337190cbb37ada38ff1148a677a14843613a1dad74d53665760a216777f0fc7cf2fc82a474ad287e909d2ac9ad80917aa96c49130890b0cbe025c8613aceb414c9d78836a2210379512007f0f5e2f09b7e938fea80a38004dcea90dd0b91c5194ad577fb7b19517ea97e2ad263fcc5df7f57e0610359512007f0fc11b5fca7cddef5270ec35ba01254d8bff046a1a58f16d3ae615c235efd6e99a35f233b2d9df2c10399512007f10006d158bec357dc0f6565462b85ef1e5e87d5cee369c1c2c136d60581e58bcb228cae652d2775b36101095120080bff580b4cfae1755ecdb2e2ae0c2b483990fa5cb9c2399d160d020784bed5b7a3f21ff80fa6e3035659f8bfcead0335f02e271d765553683562ddc26f79575675cd8b697804ccc975c5f36981141445cb43e0dfcba2ac683f805b9d9e0e32ac8907896236480245dbaddb187424137ca13e4d94ef018f882d1cbddef99eaf514f7db059bb2e8802c1012ba55f677be44aee12b03d3a63c368ae5e5852a6190909fb2cbdc9236eb8012b143da584384141e5d405cb356c8e1b3a281110443fe...86da2a51e7def0388e1365ae8d3c90cf717b215aa146138740106180f7cc5dd37f0dbf9a001004d9fe2a430fe87b5fac8e1824099ebc87ade6b13e2180f64b72615cb22da802e70779b9ede57c50286d7044d860f4f46ed4d75a1a03f6802fa8e812509acb504c67946cb36c6176442ea61614671c31fb2b3ea9410ee0249f05323df7cc47150b3930e2666b0aa3133d324c5f0a6ccf00f78ac824e72d27429ca3b8b0040080b844f577a2383ffe678227779651a13d05cdedfbba4d4e84baacc806bf2262f24c5f0dca42deb008c6559ee789c9b9f70a2c040080ce26713589dfb681da82046f8bebf1c3ba2f8e08eff1891451b75b7627bac301802f6f8ee7d8aa0aa0c3375b2e2c5cd603132474ffda5f17901bc12120b38fcb65803fae229d79e099dbfaf49bb235f5e3e2d77f5b7f56259bc06c48041519f982e580f215acd6eb8c329e53881a63d04788720e89f5ccc721c6cea7a39c589630b33480bb3286487a309e66d8e653dd425d67eeee29bbb2fc3fe73c81d0554768de3b37250f6465aec5558620d2c16c79c89610e2f05094c5d25664922271039e810e5cfc37eae3800404545ea5c1b19ab7a04f536c519aca4983ac1039951200545e98fdbe9ce6c55837576c60c7af385010020000007f0fa1f8e36558293f3a3c081fefa1ba54fb696169fcc52717f620b304734a3348ecb55211fe4a651a1034951200 / 31 nodes    
2022-04-13 17:27:38 proof size: 733.65 KB (751258 bytes)    
2022-04-13 17:27:38 compact proof size: 732.74 KB (750326 bytes)    
2022-04-13 17:27:38 zstd-compressed compact proof 732.76 KB (750350 bytes)    
2022-04-13 17:27:38 TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 1425000000, total weight = 500000000000 (0.00285) 
```

**Comment by ghzlatarev** [comment]
```
Metadata comparison:
Date: Fri Apr 22 14:01:52 UTC 2022
Reference: wss://calamari.api.onfinality.io/public-ws
Target version: manta 3.1.5-18aeacb-x86_64-linux-gnu
-------------------------------------------
              [Spec] name: calamari
                     spec_version: 3141 -> 3150
                     transaction_version: 4
          [Metadata] version: 14
           [Modules] num: 28 -> 31
                     [+] modules: XTokens, Assets, AssetManager
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 20)
                       [Timestamp] idx: 2 (calls: 1, storage: 3)
                [TransactionPause] idx: 9 (calls: 2, storage: 2)
                        [Balances] idx: [10] (calls: 6, storage: 6)
                       [Democracy] idx: [14] (calls: 25, storage: [15])
                         [Council] idx: 15 (calls: 6, storage: 7)
               [CouncilMembership] idx: [16] (calls: 7, storage: 3)
              [TechnicalCommittee] idx: [17] (calls: 6, storage: 7)
             [TechnicalMembership] idx: [18] (calls: 7, storage: 3)
                      [Authorship] idx: [20] (calls: 1, storage: 4)
               [CollatorSelection] idx: [21] (calls: 7 -> 9, storage: 6 -> 8)
                                   [+] calls: setEvictionBaseline, setEvictionTolerance
                                   [+] storage: blocksPerCollatorThisSession, evictionBaseline, evictionTolerance
                                   [-] storage: lastAuthoredBlock
                         [Session] idx: [22] (calls: 2, storage: 8)
                        [Treasury] idx: [26] (calls: 3, storage: 4)
                        [Preimage] idx: [28] (calls: 4, storage: 3)
                       [Scheduler] idx: [29] (calls: 6, storage: 3)
                       [XcmpQueue] idx: [30] (calls: 1, storage: 9)
                     [PolkadotXcm] idx: [31] (calls: 10, storage: 10)
                        [DmpQueue] idx: [33] (calls: 1, storage: 5)
                        [Multisig] idx: [41] (calls: 4, storage: 3)
                            [Sudo] idx: [42] (calls: 4, storage: 2)
                 [CalamariVesting] idx: 50 (calls: 3, storage: 3)
```
