### ISSUE TITLE
Indexer Ledger(Tracking Issue)

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#686]
- [ ] indexer(Jamie)
  - [ ] db design and IO benchmarking
  - [ ] Concurrency issues
  - [ ] `Shards` reconstruction
  - [ ] Benchmarking and performance
  - [ ] Threading model
- [ ] rpc forwarding(Yi)
  - [ ] Figure out must-have rpc methods to be forwarded
  - [ ] How to forward subscription rpc
- [ ] monitoring
  - [ ] what metrics need to be monitored
- [ ] How to globally configure the indexer server correctly
- [ ] ...

**Comment by Garandor** [comment]
tracked in https://github.com/Manta-Network/manta-indexer
